import type { Metadata } from 'next'
import { Slide, ToastContainer } from 'react-toastify'
import './globals.css'
import { Providers } from './providers'
import { Transition } from './transition'
import variables from '@/variables'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return <html lang={variables.lang}>
    <body>
      <Providers>
        <Transition>{children}</Transition>
      </Providers>
      <ToastContainer
        position='top-center'
        transition={Slide}
        theme='colored'
        draggable={false}
        // pauseOnFocusLoss={false}
        // pauseOnHover={false}
        autoClose={2000}
      // hideProgressBar={true}
      />
    </body>
  </html>
}
