import { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

const a = 1

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return <html lang='zh-CN'>
    <body>
      {children}
    </body>
  </html>
}
